language: r
cache: packages

r_packages:
  - covr
  - devtools

addons:
  apt:
    packages:
      - libnlopt-dev

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

matrix:
  fast_finish: true
  allow_failures:
    - r: devel

branches:
  only:
      - master

after_success:
  - Rscript -e 'covr::codecov()'
