language: r
cache: packages

addons:
  apt:
    packages:
      - libnlopt-dev

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel

branches:
  only:
      - master

