language: r
cache: packages

before_script:
  - Rscript -e 'devtools::install_github("hadley/dbplyr"); if (!all(c("dbplyr") %in% installed.packages())) { q(status = 1, save = "no")}'

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel

branches:
  only:
      - master

