language: r
cache: packages

before_script:
  - sudo R --vanilla -e 'install.packages("devtools")'
  - sudo R --vanilla -e 'devtools::install_github("hadley/dbplyr")'

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel

branches:
  only:
      - master

